# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4fa80b4ee67966d732f832d30a8a5c710a2e1dbe4edde991dafde9efec3328f29f02ecaa9d49a98404950494705f93a7672eb1dc869e60dc70f17b61403adde

test:
  secret_key_base: 6702d55031722f36c77f01fde5c3423b698f754ef632882d0d15d591902f0390ca9847ae1c9da2a5c39dbececa07153894469fcb452b64c38f7281f06e7ab618

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
